#COLUMNS_SOURCE = ["FILE","DATE","TARGET","FOIL","CURRENT_MAX", "CURRENT_MIN","CURRENT_AVE","CURRENT_STD","VOLTAGE_MAX","VOLTAGE_MIN","VOLTAGE_AVE","VOLTAGE_STD","HFLOW",
#    "RATIO_MAX", "RATIO_MIN","RATIO_AVE","RATIO_STD"] 
COLUMNS_SOURCE = ["FILE","DATE","TARGET","FOIL","CURRENT_MAX", "CURRENT_MIN","CURRENT_AVE","CURRENT_STD","VOLTAGE_MAX","VOLTAGE_MIN","VOLTAGE_AVE","VOLTAGE_STD","HFLOW",
    "RATIO_MAX", "RATIO_MIN","RATIO_AVE","RATIO_STD","SOURCE_PERFORMANCE_AVE","SOURCE_PERFORMANCE_STD"]
COLUMNS_VACUUM = ["FILE","DATE","TARGET","FOIL","PRESSURE_MAX","PRESSURE_MIN","PRESSURE_AVE","PRESSURE_STD"]
COLUMNS_MAGNET = ["FILE","DATE","TARGET","FOIL","CURRENT_MAX","CURRENT_MIN","CURRENT_AVE","CURRENT_STD"]
#COLUMNS_RF =  ["FILE","DATE","TARGET","FOIL","DEE1_VOLTAGE_MAX","DEE1_VOLTAGE_MIN","DEE1_VOLTAGE_AVE","DEE1_VOLTAGE_STD","DEE2_VOLTAGE_MAX","DEE2_VOLTAGE_MIN","DEE2_VOLTAGE_AVE","DEE2_VOLTAGE_STD",
#    "FORWARD_POWER_MAX","FORWARD_POWER_MIN","FORWARD_POWER_AVE","FORWARD_POWER_STD","REFLECTED_POWER_MAX","REFLECTED_POWER_MIN","REFLECTED_POWER_AVE","REFLECTED_POWER_STD",
#    "PHASE_LOAD_MAX","PHASE_LOAD_MIN","PHASE_LOAD_AVE","PHASE_LOAD_STD"]
COLUMNS_BEAM = ["FILE","DATE","TARGET","FOIL","COLL_CURRENT_L_MAX","COLL_CURRENT_L_MIN","COLL_CURRENT_L_AVE","COLL_CURRENT_L_STD","COLL_CURRENT_R_MAX","COLL_CURRENT_R_MIN","COLL_CURRENT_R_AVE","COLL_CURRENT_R_STD"
    ,"RELATIVE_COLL_CURRENT_L_MAX","RELATIVE_COLL_CURRENT_L_MIN","RELATIVE_COLL_CURRENT_L_AVE","RELATIVE_COLL_CURRENT_L_STD",
    "RELATIVE_COLL_CURRENT_R_MAX","RELATIVE_COLL_CURRENT_R_MIN","RELATIVE_COLL_CURRENT_R_AVE","RELATIVE_COLL_CURRENT_R_STD",
    "TARGET_CURRENT_MAX","TARGET_CURRENT_MIN","TARGET_CURRENT_AVE","TARGET_CURRENT_STD","FOIL_CURRENT_MAX","FOIL_CURRENT_MIN","FOIL_CURRENT_AVE","FOIL_CURRENT_STD",
    "RELATIVE_TARGET_CURRENT_MAX","RELATIVE_TARGET_CURRENT_MIN","RELATIVE_TARGET_CURRENT_AVE","RELATIVE_TARGET_CURRENT_STD",
    "EXTRACTION_LOSSES_MAX","EXTRACTION_LOSSES_MIN","EXTRACTION_LOSSES_AVE","EXTRACTION_LOSSES_STD",
    "RELATIVE_COLL_CURRENT_MAX","RELATIVE_COLL_CURRENT_MIN","RELATIVE_COLL_CURRENT_AVE","RELATIVE_COLL_CURRENT_STD"]
COLUMNS_EXTRACTION = ["FILE","DATE","TARGET","FOIL","CAROUSEL_POSITION_MAX","CAROUSEL_POSITION_MIN","CAROUSEL_POSITION_AVE","CAROUSEL_POSITION_STD"
    ,"BALANCE_POSITION_MAX","BALANCE_POSITION_MIN","BALANCE_POSITION_AVE","BALANCE_POSITION_STD"]
COLUMNS_TRANSMISSION = ["FILE","DATE","TARGET","TRANSMISSION_AVE","TRANSMISSION_STD","FOIL"]
COLUMNS_FILLING = ["FILE","TIME_LIST","DATE","TARGET","RELATIVE_VOLUME"]
COLUMNS_FLUCTUATIONS = ["FILE","TIME_LIST","DATE","TARGET","PRESSURE_FLUCTUATIONS"]

COLUMNS_RF =  ["FILE","DATE","TARGET","FOIL","DEE1_VOLTAGE_MAX","DEE1_VOLTAGE_MIN","DEE1_VOLTAGE_AVE","DEE1_VOLTAGE_STD","DEE2_VOLTAGE_MAX","DEE2_VOLTAGE_MIN","DEE2_VOLTAGE_AVE","DEE2_VOLTAGE_STD",
    "FORWARD_POWER_MAX","FORWARD_POWER_MIN","FORWARD_POWER_AVE","FORWARD_POWER_STD","REFLECTED_POWER_MAX","REFLECTED_POWER_MIN","REFLECTED_POWER_AVE","REFLECTED_POWER_STD",
    "PHASE_LOAD_MAX","PHASE_LOAD_MIN","PHASE_LOAD_AVE","PHASE_LOAD_STD",
    "FLAP1_MAX","FLAP1_MIN","FLAP1_AVE","FLAP1_STD","FLAP2_MAX","FLAP2_MIN","FLAP2_AVE","FLAP2_STD"]
#
COLUMN_RF = ["DEE1 VOLTAGE [kV]","DEE2 VOLTAGE [kV]","FORWARDED POWER [kW]","REFLECTED POWER [kW]","FLAP1 POSITION [%]","FLAP2 POSITION [%]"]
COLUMNS_RF_AVE =  ["DEE1_VOLTAGE_AVE","DEE2_VOLTAGE_AVE","FORWARD_POWER_AVE","REFLECTED_POWER_AVE","FLAP1_AVE","FLAP2_AVE"]
COLUMNS_RF_STD =  ["DEE1_VOLTAGE_STD","DEE2_VOLTAGE_STD","FORWARD_POWER_STD","REFLECTED_POWER_STD","FLAP1_STD","FLAP2_STD"]
COLUMN_BEAM = ["COLL L [uA]","COLL R [uA]","COLL REL L[%]","COLL REL R[%]","TARGET[uA]","FOIL[uA]"]
COLUMNS_BEAM_AVE = ["COLL_CURRENT_R_AVE","COLL_CURRENT_R_AVE",
            "RELATIVE_COLL_CURRENT_L_AVE",
            "RELATIVE_COLL_CURRENT_R_AVE",
             "TARGET_CURRENT_AVE",
             "FOIL_CURRENT_AVE"]
COLUMNS_BEAM_STD = ["COLL_CURRENT_L_STD","COLL_CURRENT_R_STD","RELATIVE_COLL_CURRENT_L_STD","RELATIVE_COLL_CURRENT_R_STD","TARGET_CURRENT_STD",
         "FOIL_CURRENT_STD"]
COLUMN_EXTRACTION = ["CAROUSSEL [%]","BALANCE [%]"]
COLUMNS_EXTRACTION_AVE = ["CAROUSEL_POSITION_AVE","BALANCE_POSITION_AVE"]
COLUMNS_EXTRACTION_STD = ["CAROUSEL_POSITION_STD","BALANCE_POSITION_STD"]
COLUMN_ION_SOURCE = ["CURRENT [mA]","VOLTAGE [V]""RATIO [mA/uA]"]
COLUMNS_ION_SOURCE_AVE = ["CURRENT_AVE","VOLTAGE_AVE","RATIO_AVE"]
COLUMNS_ION_SOURCE_STD = ["CURRENT_STD","VOLTAGE_STD","RATIO_STD"]
COLUMN_VACUUM = ["PRESSURE [10-5 mbar]"]
COLUMNS_VACUUM_AVE = ["PRESSURE_AVE"]
COLUMNS_VACUUM_STD = ["PRESSURE_STD"]
COLUMN_MAGNET = [str("MAGNET CURRENT [A]")]
COLUMNS_MAGNET_AVE = ["CURRENT_AVE","CURRENT_STD"]
COLUMNS_MAGNET_STD = ["CURRENT_STD"]
COLUMN_LOSSES = ["EXTRACTION LOSSES [%]"]
COLUMNS_LOSSES_AVE = ["EXTRACTION_LOSSES_AVE"]  
COLUMNS_LOSSES_STD = ["EXTRACTION_LOSSES_STD"]
COLUMN_TRANSMISSION = ["TRANSMISSION"]
COLUMNS_TRANSMISSION_AVE = ["TRANSMISSION_AVE"]
COLUMNS_TRANSMISSION_STD = ["TRANSMISSION_STD"]

import pandas as pd
def flags(self): 
        self.current_row = 0
        self.current_row_folder = 0
        self.current_row_statistics = 0
        self.current_row_analysis = 0 
        self.row_to_plot = 0
        self.current_row_observables = 0
        self.current_row_observables_tab3 = 0      
        self.target_1_value = "0"
        self.target_2_value = "0"
        self.max_min_value = "0"        
        self.week_value = "0"
        self.day_value = "1"
        self.flag_no_gap = "1"

def initial_df(self):               
        self.df_source = pd.DataFrame(columns=COLUMNS_SOURCE)
        self.df_vacuum = pd.DataFrame(columns=COLUMNS_VACUUM)
        self.df_magnet = pd.DataFrame(columns=COLUMNS_MAGNET)
        self.df_beam = pd.DataFrame(columns=COLUMNS_BEAM )
        self.df_rf = pd.DataFrame(columns=COLUMNS_RF)
        self.df_extraction = pd.DataFrame(columns=COLUMNS_EXTRACTION)
        self.df_transmission = pd.DataFrame(columns=COLUMNS_TRANSMISSION)
        self.df_filling_volume = pd.DataFrame(columns=COLUMNS_FILLING)
        self.df_pressure_fluctuations = pd.DataFrame(columns=COLUMNS_FLUCTUATIONS)


