volume_file = tfs.read("/Users/anagtv/Documents/OneDrive/046 - Medical Devices/Mantenimientos ciclotrones/JNS/ANALYSIS/20210712_22/table_summary_volume.out")
fig3, ax3 = plt.subplots()
ax3.scatter(volume_file.FILE[volume_file.TARGET == '1'],volume_file.PRESSURE_FINAL[volume_file.TARGET == '1'],label="FINAL T 1")
ax3.scatter(volume_file.FILE[volume_file.TARGET == '4'],volume_file.PRESSURE_FINAL[volume_file.TARGET == '4'],label="FINAL T 4")
ax3.set_xlabel("File Number")
ax3.set_ylabel("Pressure [PSI]")
plt.legend(loc='best')
plt.savefig("/Users/anagtv/Documents/OneDrive/046 - Medical Devices/Mantenimientos ciclotrones/JNS/ANALYSIS/20210712_22/pressure_final.pdf")
fig3, ax3 = plt.subplots()
ax3.set_xlabel("File Number")
ax3.set_ylabel("Pressure [PSI]")
ax3.scatter(volume_file.FILE[volume_file.PRESSURE_INITIAL < 400],volume_file.PRESSURE_INITIAL[volume_file.PRESSURE_INITIAL < 400],label="INTIAL")
plt.legend(loc='best')
plt.savefig("/Users/anagtv/Documents/OneDrive/046 - Medical Devices/Mantenimientos ciclotrones/JNS/ANALYSIS/20210712_22/pressure_initial.pdf")
